if(instance_exists(obj_npc_parent)) obj_npc_parent.visible = true;
if(instance_exists(obj_plant_tomato))obj_plant_tomato.visible = false;
if(instance_exists(obj_plant_carrot))obj_plant_carrot.visible = false;
if(instance_exists(obj_plant_cucumber))obj_plant_cucumber.visible = false;
if(instance_exists(obj_plant_lettuce))obj_plant_lettuce.visible = false;
if(instance_exists(obj_plant_potato))obj_plant_potato.visible = false;
inst_37AECBB4.visible = true;
if(instance_exists(inst_40D07232)) inst_40D07232.visible = false;
layer_set_visible("UI_layer",false);
layer_set_visible("Money",true);
layer_set_visible("UILayer_Inventory",true);
layer_set_visible("Fridge_interior",false);
obj_lock.visible = true;
layer_set_visible("Recipe_fish",false);
layer_set_visible("Recipe_pasta",false);
layer_set_visible("Recipe_salad",false);
layer_set_visible("Recipe_soup",false);